services:
  helidon-se:
    container_name: helidon-se
    image: a002k/helidon-se:bot
    environment:
      - BOT_ADMIN=${BOT_ADMIN}
      - BOT_TOKEN=${BOT_TOKEN}
    ports:
      - "8080:8080"
    networks:
      - bridge-net
    volumes:
      - helidon-se:/home/runner/data

networks:
  bridge-net:
    driver: bridge

volumes:
  helidon-se: