services:
  helidon-se:
    container_name: helidon-se
    image: a002k/helidon-se:latest
    environment:
      - APP_GREETING=${APP_GREETING:-'Greeting from docker-compose'}
    ports:
      - "8080:8080"
    networks:
      - bridge-net
    volumes:
      - helidon-se:/home/runner/data

networks:
  bridge-net:
    driver: bridge

volumes:
  helidon-se: